version: '3.7'
services:
  db:
    build: ./mydocker/.docker/mysql
    container_name: db
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: trilha
      MYSQL_ROOT_PASSWORD: "1234"
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
  php:
    build: ./mydocker/.docker/php
    container_name: 'php'
    restart: 'always'
    ports:
      - "80:80"
    links:
      - db
      - redis
    volumes:
      - /var/www/html/logdocker/var/log:/var/log/
      # - ./:/var/www
      - ./:/var/www/html
  redis:
    image: redis:4.0
    container_name: 'redis'
    restart: 'always'
    command: redis-server --requirepass teste
    ports:
      - "6378:6379"